spring:
  main.banner-mode: "off"
  zipkin:
    base-url: http://tracing:9411/
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://auth:8080/auth/realms/spring-cloud-demo/protocol/openid-connect/certs'
