logging:
  level:
    net.trajano.spring.swarm: DEBUG
    # org.springframework.cloud.gateway: DEBUG
    # org.springframework.cloud.gateway: WARN
    org.springframework: DEBUG
spring:
  cloud:
    loadbalancer:
      cache:
        ttl: 5s
        enabled: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 434054152947-a0tdkv2u4oiebstd6i46urvorkspqptu.apps.googleusercontent.com
            client-secret: v6R-MtfKDY3V-9UGcDnROXbU
docker.discovery.networks: spring_default
management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: "*"