version: "3.7"
services:
  configserver:
    image: trajano/cloud-config
    environment:
      SPRING_ZIPKIN_BASE-URL: http://tracing:9411/
      SPRING_ZIPKIN_SERVICE_NAME: config
      SPRING_PROFILES_ACTIVE: native
    deploy:
      replicas: 2
      update_config:
        order: start-first
      restart_policy:
        condition: any
        delay: 10s
      labels:
        - spring.service.discoverable=true
  api:
    image: trajano/cloud-gateway
    environment:
      SPRING_ZIPKIN_BASE-URL: http://tracing:9411/
      SPRING_ZIPKIN_SERVICE_NAME: gateway
      #      SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED: "true"
      #      SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED: "true"
      SPRING_CLOUD_CONFIG_URI: http://configserver:8080/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3211:8080
    deploy:
      replicas: 1
      update_config:
        order: start-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 2
  auth:
    image: trajano/cloud-auth
    environment:
      SPRING_ZIPKIN_BASE-URL: http://tracing:9411/
      SPRING_CLOUD_CONFIG_URI: http://configserver:8080/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3211:8080
    deploy:
      replicas: 1
      update_config:
        order: start-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 2
  tracing:
    image: openzipkin/zipkin
    deploy:
      replicas: 1
      update_config:
        order: start-first
      restart_policy:
        condition: any
        delay: 10s
      labels:
        - spring.service.discoverable=true
        - spring.service.port=9441
  whoami:
    image: containous/whoami
    deploy:
      replicas: 2
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: '0.5'
          memory: 32M
      labels:
        - spring.service.discoverable=true
        - spring.service.port=80

