spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
        - RemoveRequestHeader=Cookie
      enabled: true
      discovery:
        locator:
          enabled: true
    loadbalancer:
      ribbon:
        enabled: false
