spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
        - RemoveRequestHeader=Cookie
      discovery:
        locator:
          enabled: true
          predicates:
            - Path='/*/'+serviceId+'/**'
          filters:
            - StripPrefix=2
      enabled: true
    loadbalancer:
      ribbon:
        enabled: false
