spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          url-expression: "uri"
          enabled: true  # default false
logging:
  level:
    net.trajano.spring.swarm: DEBUG
    org:
      springframework:
        cloud:
          gateway: DEBUG